<?php
// $Id$

define ('UC_OUT_OF_STOCK_DEFAULT_HTML', t('<span style="color: red;">Out of stock</span>'));

function uc_out_of_stock_form_alter(&$form, $form_state, $form_id) {
  $forms = array('uc_product_add_to_cart_form', 'uc_catalog_buy_it_now_form');
  foreach ($forms as $id) {
    if ( substr($form_id, 0, strlen($id)) == $id ) {
      drupal_add_js(drupal_get_path('module', 'uc_out_of_stock') . '/uc_out_of_stock.js');
      drupal_add_css(drupal_get_path('module', 'uc_out_of_stock') . '/uc_out_of_stock.css');
    }
  }
}

function uc_out_of_stock_menu() {
  $items = array();

  $items['admin/store/settings/uc_out_of_stock'] = array(
    'title' => 'Out of Stock Settings',
    'access arguments' => array('administer store'),
    'description' => 'Configure out of stock settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uc_out_of_stock_settings'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['uc_out_of_stock/query'] = array(
    'title' => 'stock query',
    'page callback' => 'uc_out_of_stock_query',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function uc_out_of_stock_query() {
  $attrs = array();
  $response = array();

  $nid = $_POST['nid'];
  foreach ( $_POST as $key => $value ) {
    if ( substr($key, 0, 4) == 'attr' ) {
      $attrs[substr($key, 4)] = $value;
    }
  }

  // if attributes module exists, and product has attributes first search for attributes
  // if attributes module exists, and product has attributes first search for attributes
  $post_attrs = count($attrs);
  $sql = "SELECT %s FROM {uc_product_adjustments} upa LEFT JOIN {uc_product_stock} ups ON ups.sku = upa.model WHERE upa.nid = %d";
  $db_attrs = db_result(db_query($sql, 'COUNT(*)', $nid));
  if (module_exists('uc_attribute') && $post_attrs && $db_attrs > 0) {
    $result = db_query($sql, '*', $nid);
    while ($row = db_fetch_object($result)) {
      $combination = unserialize($row->combination);
      // Apparently, on D6, one entry of the stock table has always the main SKU regardless the adjustments settings
      // Therefor, if the join gives a null record for the stock table, the main sku will be queried as well
      if ( isset($row->sku) && $combination == $attrs ) {
        $combination_found = TRUE;
        // Only check if active
        if ($row->active) {
          $response['stock'] = $row->stock;
          if ( $row->stock <= 0 ) {
            $response['html'] = check_markup(variable_get('uc_out_of_stock_text', UC_OUT_OF_STOCK_DEFAULT_HTML), variable_get('uc_out_of_stock_format', FILTER_FORMAT_DEFAULT), FALSE);
          }
        }
      }
    }

    // If the combination was not found, and all attributes were indeed selected, we are assuming that some
    // combination shares an SKU with the actual product, thus, the product have to be queried as well.
    if (!$combination_found) {
      $query_main_sku = TRUE;
    }
  }
  else {
    // If there are attributes for the product, but no attributes were sent, do nothing
    // as it's probably coming from the catalog table list view and we can't
    // disable the add to cart button for products with attributes
    if ($post_attrs == 0 && $db_attrs > 0) {
      $query_main_sku = FALSE;
    }
    else {
      $query_main_sku = TRUE;
    }
  }

  if ($query_main_sku) {
    // seach for main product
    $result = db_query("SELECT * FROM {uc_products} up LEFT JOIN {uc_product_stock} ups ON ups.sku = up.model WHERE up.nid = %d AND ups.active = 1", $nid);
    while ($row = db_fetch_object($result)) {
      $response['stock'] = $row->stock;
      if ( $row->stock <= 0 ) {
        $response['html'] = check_markup(variable_get('uc_out_of_stock_text', UC_OUT_OF_STOCK_DEFAULT_HTML), variable_get('uc_out_of_stock_format', FILTER_FORMAT_DEFAULT), FALSE);
      }
    }
  }

  // if there is some response, print it
  if (count($response)){
    print implode('|', $response);
  }
}

/**
 * 		the settings form
 */
function uc_out_of_stock_settings_submit($form_id, $form_values) {
  $op = isset($form_values['op']) ? $form_values['op'] : '';

  if ($op == t('Reset to defaults')) {
    variable_del('uc_out_of_stock_text');
    variable_del('uc_out_of_stock_format');
  }
  else {
    variable_set('uc_out_of_stock_text', $form_values['uc_out_of_stock_text']);
    variable_set('uc_out_of_stock_format', $form_values['format']);
  }

  if ($op == t('Reset to defaults')) {
    drupal_set_message(t('The configuration options have been reset to their default values.'));
  }
  else {
    drupal_set_message(t('The configuration options have been saved.'));
  }

  menu_rebuild();
}


function uc_out_of_stock_settings() {
  $text = check_markup(variable_get('uc_out_of_stock_text', UC_OUT_OF_STOCK_DEFAULT_HTML), variable_get('uc_out_of_stock_format', FILTER_FORMAT_DEFAULT), FALSE);
  $description = '<div class="description">This is the value below rendered as you would expect to see it</div>';
  $text = '<div style="border: 1px solid lightgrey; padding: 10px;">' . $text . '</div>' . $description;

  $form['uc_out_of_stock_demo'] = array(
    '#type' => 'markup',
    '#value' => $text,
  );

  $form['uc_out_of_stock_text'] = array(
    '#type' => 'textarea',
    '#title' => t('Out of stock replacement HTML'),
    '#default_value' => variable_get('uc_out_of_stock_text', UC_OUT_OF_STOCK_DEFAULT_HTML),
    '#description' => t('The HTML that will replace the Add To Cart button if no stock is available.'),
  );

  $form['uc_out_of_stock_format'] = filter_form(variable_get('uc_out_of_stock_format', FILTER_FORMAT_DEFAULT));

  $form['buttons']['submit'] = array('#type' => 'submit', '#value' => t('Save configuration') );
  $form['buttons']['reset'] = array('#type' => 'submit', '#value' => t('Reset to defaults') );

  return $form;
}